export const PRESUPUESTO_LIST_REQUEST = 'PRESUPUESTO_LIST_REQUEST'
export const PRESUPUESTO_LIST_SUCCESS = 'PRESUPUESTO_LIST_SUCCESS'
export const PRESUPUESTO_LIST_FAIL = 'PRESUPUESTO_LIST_FAIL'
export const PRESUPUESTO_LIST_RESET = 'PRESUPUESTO_LIST_RESET'

export const PRESUPUESTO_DETAILS_REQUEST = 'PRESUPUESTO_DETAILS_REQUEST'
export const PRESUPUESTO_DETAILS_SUCCESS = 'PRESUPUESTO_DETAILS_SUCCESS'
export const PRESUPUESTO_DETAILS_FAIL = 'PRESUPUESTO_DETAILS_FAIL'

export const PRESUPUESTO_DELETE_REQUEST = 'PRESUPUESTO_DELETE_REQUEST'
export const PRESUPUESTO_DELETE_SUCCESS = 'PRESUPUESTO_DELETE_SUCCESS'
export const PRESUPUESTO_DELETE_FAIL = 'PRESUPUESTO_DELETE_FAIL'

export const PRESUPUESTO_CREATE_REQUEST = 'PRESUPUESTO_CREATE_REQUEST'
export const PRESUPUESTO_CREATE_SUCCESS = 'PRESUPUESTO_CREATE_SUCCESS'
export const PRESUPUESTO_CREATE_FAIL = 'PRESUPUESTO_CREATE_FAIL'
export const PRESUPUESTO_CREATE_RESET = 'PRESUPUESTO_CREATE_RESET'

export const PRESUPUESTO_UPDATE_REQUEST = 'PRESUPUESTO_UPDATE_REQUEST'
export const PRESUPUESTO_UPDATE_SUCCESS = 'PRESUPUESTO_UPDATE_SUCCESS'
export const PRESUPUESTO_UPDATE_FAIL = 'PRESUPUESTO_UPDATE_FAIL'
export const PRESUPUESTO_UPDATE_RESET = 'PRESUPUESTO_UPDATE_RESET'

export const PRESUPUESTO_CREATE_REVIEW_REQUEST = 'PRESUPUESTO_CREATE_REVIEW_REQUEST'
export const PRESUPUESTO_CREATE_REVIEW_SUCCESS = 'PRESUPUESTO_CREATE_REVIEW_SUCCESS'
export const PRESUPUESTO_CREATE_REVIEW_FAIL = 'PRESUPUESTO_CREATE_REVIEW_FAIL'
export const PRESUPUESTO_CREATE_REVIEW_RESET = 'PRESUPUESTO_CREATE_REVIEW_RESET'

export const PRESUPUESTO_TOP_REQUEST = 'PRESUPUESTO_TOP_REQUEST'
export const PRESUPUESTO_TOP_SUCCESS = 'PRESUPUESTO_TOP_SUCCESS'
export const PRESUPUESTO_TOP_FAIL = 'PRESUPUESTO_TOP_FAIL'
